// <auto-generated />
using System;
using Algorhythm.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Algorhythm.Data.Migrations
{
    [DbContext(typeof(AlgorhythmDbContext))]
    [Migration("20220228211223_User")]
    partial class User
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Algorhythm.Business.Models.Alternative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Alternatives");
                });

            modelBuilder.Entity("Algorhythm.Business.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Algorhythm.Business.Models.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Algorhythm.Business.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExerciseUser", b =>
                {
                    b.Property<Guid>("ExercisesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExercisesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ExerciseUser");
                });

            modelBuilder.Entity("Algorhythm.Business.Models.Alternative", b =>
                {
                    b.HasOne("Algorhythm.Business.Models.Exercise", "Exercise")
                        .WithMany("Alternatives")
                        .HasForeignKey("ExerciseId")
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Algorhythm.Business.Models.Exercise", b =>
                {
                    b.HasOne("Algorhythm.Business.Models.Module", "Module")
                        .WithMany("Exercises")
                        .HasForeignKey("ModuleId")
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("ExerciseUser", b =>
                {
                    b.HasOne("Algorhythm.Business.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesId")
                        .IsRequired();

                    b.HasOne("Algorhythm.Business.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .IsRequired();
                });

            modelBuilder.Entity("Algorhythm.Business.Models.Exercise", b =>
                {
                    b.Navigation("Alternatives");
                });

            modelBuilder.Entity("Algorhythm.Business.Models.Module", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
